openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Access'
paths: {}
components:
  schemas:

    Network:
      type: object
      properties:
        country:
          $ref: 'common.yaml#/components/schemas/Country'
