openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Test'

paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ResponseBody'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ResponseBody'

components:
  schemas: {}
